# Generated by Django 5.2 on 2025-05-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformintegration',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='Custom HTTP headers for API requests'),
        ),
    ]
