# Generated by Django 5.2 on 2025-05-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_platformintegration_headers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformintegration',
            name='auth_data',
        ),
        migrations.RemoveField(
            model_name='platformintegration',
            name='auth_type',
        ),
    ]
