# Generated by Django 5.2 on 2025-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('phone', 'Phone Call'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('other', 'Other')], default='website', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('appointment_scheduled', 'Appointment Scheduled'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=50),
        ),
    ]
