# Generated by Django 5.2 on 2025-05-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_source_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leadcommunication',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
