# Generated by Django 5.2 on 2025-05-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_id_alter_leadcommunication_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted_by_phone', 'Contacted By Phone'), ('contacted_by_sms', 'Contacted By SMS'), ('qualified', 'Qualified'), ('appointment_scheduled', 'Appointment Scheduled'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=50),
        ),
    ]
