# Generated by Django 5.2 on 2025-10-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0004_pluginerror_plugindependency_pluginexecutionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluginsetting',
            options={'ordering': ['is_standard', 'category', 'setting_name']},
        ),
        migrations.AddField(
            model_name='pluginsetting',
            name='category',
            field=models.CharField(blank=True, help_text='Setting category (debugging, notifications, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='pluginsetting',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this setting does'),
        ),
        migrations.AddField(
            model_name='pluginsetting',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='Whether this is a standard setting'),
        ),
    ]
