# Generated by Django 5.2 on 2025-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessconfiguration',
            name='follow_up_attempts',
        ),
        migrations.RemoveField(
            model_name='businessconfiguration',
            name='follow_up_interval',
        ),
        migrations.RemoveField(
            model_name='businessconfiguration',
            name='lead_notification_email',
        ),
        migrations.RemoveField(
            model_name='businessconfiguration',
            name='sms_enabled',
        ),
        migrations.RemoveField(
            model_name='businessconfiguration',
            name='webhook_secret',
        ),
        migrations.AddField(
            model_name='businessconfiguration',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessconfiguration',
            name='twilio_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
