# Generated by Django 5.2 on 2025-05-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_smtpconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='identifier',
            field=models.SlugField(blank=True, help_text='Unique identifier for this service item (e.g., number_of_bedrooms)', max_length=120),
        ),
    ]
