# Generated by Django 5.2 on 2025-05-08 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_serviceitem_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='default_payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('square', 'Square')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SquareCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='square_credentials', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='StripeCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_publishable_key', models.CharField(blank=True, max_length=255, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_credentials', to='business.business')),
            ],
        ),
    ]
