# Generated by Django 5.2 on 2025-05-08 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_default_payment_method_alter_business_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecredentials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripecredentials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
