# Generated by Django 5.2 on 2025-07-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_stripecredentials_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfiguration',
            name='invoice_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('percentage', 'Percentage of Base Price'), ('hourly', 'Hourly Rate'), ('per_unit', 'Per Unit'), ('free', 'Free')], default='fixed', max_length=20),
        ),
    ]
