# Generated by Django 5.2 on 2025-07-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_businessconfiguration_invoice_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='field_options',
            field=models.JSONField(blank=True, help_text='Options for select fields, stored as JSON array', null=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('number', 'Number Input'), ('boolean', 'Yes/No Checkbox'), ('select', 'Dropdown Select')], default='text', help_text='Type of field to display for this item', max_length=20),
        ),
    ]
