# Generated by Django 5.2 on 2025-05-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
