# Generated by Django 5.2 on 2025-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_id_alter_staffmember_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingserviceitem',
            name='boolean_value',
            field=models.BooleanField(blank=True, help_text='Value for boolean fields (yes/no)', null=True),
        ),
        migrations.AddField(
            model_name='bookingserviceitem',
            name='number_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value for number fields and non-free items', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingserviceitem',
            name='select_value',
            field=models.CharField(blank=True, help_text='Selected option for dropdown fields', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookingserviceitem',
            name='text_value',
            field=models.CharField(blank=True, help_text='Value for text input fields', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookingserviceitem',
            name='textarea_value',
            field=models.TextField(blank=True, help_text='Value for textarea fields', null=True),
        ),
    ]
