# Generated by Django 5.2 on 2025-10-07 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingserviceitem_boolean_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Booking Created'), ('confirmed', 'Booking Confirmed'), ('cancelled', 'Booking Cancelled'), ('rescheduled', 'Booking Rescheduled'), ('completed', 'Booking Completed'), ('no_show', 'Marked as No Show'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added')], max_length=20)),
                ('description', models.TextField(help_text='Description of the event')),
                ('reason', models.TextField(blank=True, help_text='Reason for cancellation or reschedule', null=True)),
                ('old_date', models.DateField(blank=True, help_text='Previous date for reschedule events', null=True)),
                ('old_start_time', models.TimeField(blank=True, help_text='Previous start time for reschedule events', null=True)),
                ('old_end_time', models.TimeField(blank=True, help_text='Previous end time for reschedule events', null=True)),
                ('new_date', models.DateField(blank=True, help_text='New date for reschedule events', null=True)),
                ('new_start_time', models.TimeField(blank=True, help_text='New start time for reschedule events', null=True)),
                ('new_end_time', models.TimeField(blank=True, help_text='New end time for reschedule events', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Booking Event',
                'verbose_name_plural': 'Booking Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
