# Generated by Django 5.2 on 2025-10-07 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingevent'),
        ('business', '0011_serviceitem_option_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(help_text='Unique key for this event type', max_length=50)),
                ('name', models.CharField(help_text='Display name for this event type', max_length=100)),
                ('icon', models.CharField(default='fa-info-circle', help_text='FontAwesome icon class', max_length=50)),
                ('color', models.CharField(default='secondary', help_text='Bootstrap color class', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this event type is active')),
                ('show_in_timeline', models.BooleanField(default=True, help_text='Display in booking timeline')),
                ('requires_reason', models.BooleanField(default=False, help_text='Requires reason/note when triggered')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_event_types', to='business.business')),
            ],
            options={
                'verbose_name': 'Booking Event Type',
                'verbose_name_plural': 'Booking Event Types',
                'ordering': ['business', 'display_order', 'name'],
                'unique_together': {('business', 'event_key')},
            },
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='event_type',
            field=models.ForeignKey(help_text='Type of event', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='bookings.bookingeventtype'),
        ),
        migrations.CreateModel(
            name='ReminderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_key', models.CharField(help_text='Unique key for this reminder type', max_length=50)),
                ('name', models.CharField(help_text='Display name for this reminder type', max_length=100)),
                ('icon', models.CharField(default='fa-bell', help_text='FontAwesome icon class', max_length=50)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this reminder type is active')),
                ('default_hours_before', models.IntegerField(default=24, help_text='Default hours before appointment to send')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_types', to='business.business')),
            ],
            options={
                'verbose_name': 'Reminder Type',
                'verbose_name_plural': 'Reminder Types',
                'ordering': ['business', 'display_order', 'name'],
                'unique_together': {('business', 'reminder_key')},
            },
        ),
        migrations.AlterField(
            model_name='bookingreminder',
            name='reminder_type',
            field=models.ForeignKey(help_text='Type of reminder', on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='bookings.remindertype'),
        ),
    ]
